apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_ROOT_USER
              value: admin
            - name: MONGODB_ROOT_PASSWORD
              value: admin
            - name: MONGODB_USERNAME
              value: admin
            - name: MONGODB_PASSWORD
              value: admin
            - name: MONGODB_DATABASE
              value: lanchonete
